/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -i qbinstr.ggo -f args_parser -a args_info_t -F args 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "args.h"

const char *args_info_t_purpose = "Simple dynamic binary instrumentation.";

const char *args_info_t_usage = "Usage: qbinstr [-qbgrimey] -- <app to run>";

const char *args_info_t_versiontext = "";

const char *args_info_t_description = "";

const char *args_info_t_help[] = {
  "  -h, --help     Print help and exit",
  "  -V, --version  Print version and exit",
  "  -e, --expand   Expand single-instruction rep/repne loops  (default=off)",
  "  -b, --bytes    Log bytecodes  (default=off)",
  "  -m, --memory   Log memory access  (default=off)",
  "  -q, --quiet    Do not disassemble instructions  (default=on)",
  "  -g, --general  Log general registers value  (default=off)",
  "  -y, --hybrid   Use inlined code to cache registers and make fewer clean calls\n                   (default=off)",
  "  -i, --inline   Use inline code for improved performance  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
} args_parser_arg_type;

static
void clear_given (struct args_info_t *args_info);
static
void clear_args (struct args_info_t *args_info);

static int
args_parser_internal (int argc, char **argv, struct args_info_t *args_info,
                        struct args_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct args_info_t *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->expand_given = 0 ;
  args_info->bytes_given = 0 ;
  args_info->memory_given = 0 ;
  args_info->quiet_given = 0 ;
  args_info->general_given = 0 ;
  args_info->hybrid_given = 0 ;
  args_info->inline_given = 0 ;
}

static
void clear_args (struct args_info_t *args_info)
{
  FIX_UNUSED (args_info);
  args_info->expand_flag = 0;
  args_info->bytes_flag = 0;
  args_info->memory_flag = 0;
  args_info->quiet_flag = 1;
  args_info->general_flag = 0;
  args_info->hybrid_flag = 0;
  args_info->inline_flag = 0;
  
}

static
void init_args_info(struct args_info_t *args_info)
{


  args_info->help_help = args_info_t_help[0] ;
  args_info->version_help = args_info_t_help[1] ;
  args_info->expand_help = args_info_t_help[2] ;
  args_info->bytes_help = args_info_t_help[3] ;
  args_info->memory_help = args_info_t_help[4] ;
  args_info->quiet_help = args_info_t_help[5] ;
  args_info->general_help = args_info_t_help[6] ;
  args_info->hybrid_help = args_info_t_help[7] ;
  args_info->inline_help = args_info_t_help[8] ;
  
}

void
args_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(ARGS_PARSER_PACKAGE_NAME) ? ARGS_PARSER_PACKAGE_NAME : ARGS_PARSER_PACKAGE),
     ARGS_PARSER_VERSION);

  if (strlen(args_info_t_versiontext) > 0)
    printf("\n%s\n", args_info_t_versiontext);
}

static void print_help_common(void) {
  args_parser_print_version ();

  if (strlen(args_info_t_purpose) > 0)
    printf("\n%s\n", args_info_t_purpose);

  if (strlen(args_info_t_usage) > 0)
    printf("\n%s\n", args_info_t_usage);

  printf("\n");

  if (strlen(args_info_t_description) > 0)
    printf("%s\n\n", args_info_t_description);
}

void
args_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (args_info_t_help[i])
    printf("%s\n", args_info_t_help[i++]);
}

void
args_parser_init (struct args_info_t *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
args_parser_params_init(struct args_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct args_parser_params *
args_parser_params_create(void)
{
  struct args_parser_params *params = 
    (struct args_parser_params *)malloc(sizeof(struct args_parser_params));
  args_parser_params_init(params);  
  return params;
}



static void
args_parser_release (struct args_info_t *args_info)
{

  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
args_parser_dump(FILE *outfile, struct args_info_t *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", ARGS_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->expand_given)
    write_into_file(outfile, "expand", 0, 0 );
  if (args_info->bytes_given)
    write_into_file(outfile, "bytes", 0, 0 );
  if (args_info->memory_given)
    write_into_file(outfile, "memory", 0, 0 );
  if (args_info->quiet_given)
    write_into_file(outfile, "quiet", 0, 0 );
  if (args_info->general_given)
    write_into_file(outfile, "general", 0, 0 );
  if (args_info->hybrid_given)
    write_into_file(outfile, "hybrid", 0, 0 );
  if (args_info->inline_given)
    write_into_file(outfile, "inline", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
args_parser_file_save(const char *filename, struct args_info_t *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", ARGS_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = args_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
args_parser_free (struct args_info_t *args_info)
{
  args_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
args_parser (int argc, char **argv, struct args_info_t *args_info)
{
  return args_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
args_parser_ext (int argc, char **argv, struct args_info_t *args_info,
                   struct args_parser_params *params)
{
  int result;
  result = args_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      args_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
args_parser2 (int argc, char **argv, struct args_info_t *args_info, int override, int initialize, int check_required)
{
  int result;
  struct args_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = args_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      args_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
args_parser_required (struct args_info_t *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see args_parser_params.check_ambiguity
 * @param override @see args_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               args_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  default:
    break;
  };


  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
args_parser_internal (
  int argc, char **argv, struct args_info_t *args_info,
                        struct args_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct args_info_t local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    args_parser_init (args_info);

  args_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "expand",	0, NULL, 'e' },
        { "bytes",	0, NULL, 'b' },
        { "memory",	0, NULL, 'm' },
        { "quiet",	0, NULL, 'q' },
        { "general",	0, NULL, 'g' },
        { "hybrid",	0, NULL, 'y' },
        { "inline",	0, NULL, 'i' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVebmqgyi", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          args_parser_print_help ();
          args_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          args_parser_print_version ();
          args_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'e':	/* Expand single-instruction rep/repne loops.  */
        
        
          if (update_arg((void *)&(args_info->expand_flag), 0, &(args_info->expand_given),
              &(local_args_info.expand_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "expand", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Log bytecodes.  */
        
        
          if (update_arg((void *)&(args_info->bytes_flag), 0, &(args_info->bytes_given),
              &(local_args_info.bytes_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "bytes", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Log memory access.  */
        
        
          if (update_arg((void *)&(args_info->memory_flag), 0, &(args_info->memory_given),
              &(local_args_info.memory_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "memory", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Do not disassemble instructions.  */
        
        
          if (update_arg((void *)&(args_info->quiet_flag), 0, &(args_info->quiet_given),
              &(local_args_info.quiet_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "quiet", 'q',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Log general registers value.  */
        
        
          if (update_arg((void *)&(args_info->general_flag), 0, &(args_info->general_given),
              &(local_args_info.general_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "general", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'y':	/* Use inlined code to cache registers and make fewer clean calls.  */
        
        
          if (update_arg((void *)&(args_info->hybrid_flag), 0, &(args_info->hybrid_given),
              &(local_args_info.hybrid_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "hybrid", 'y',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Use inline code for improved performance.  */
        
        
          if (update_arg((void *)&(args_info->inline_flag), 0, &(args_info->inline_given),
              &(local_args_info.inline_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "inline", 'i',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", ARGS_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  args_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  args_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
